In [1]:
import pandas as pd
import io
import requests

ModuleNotFoundError: No module named 'nfl_players'

In [3]:
%store -r df
df

,name,first_name,last_name,birth_city,birth_state,birth_country,birth_date,college,draft_team,draft_round,...,draft_year,position,height,weight,death_date,death_city,death_state,death_country,year_start,year_end
0,Isaako Aaitui,Isaako,Aaitui,NaN,NaN,NaN,1/25/1987,NaN,NaN,NaN,...,NaN,NT,4-Jun,315.0,NaN,NaN,NaN,NaN,2013,2013
1,Faye Abbott,Faye,Abbott,Clearport,OH,USA,1895-08-16,Syracuse,NaN,NaN,...,NaN,BB-FB-TB-QB-WB-,8-May,182.0,1/22/1965,Dayton,OH,NaN,1921,1929
2,Vince Abbott,Vince,Abbott,London,NaN,England,5/31/1958,Washington,NaN,NaN,...,NaN,K,11-May,207.0,NaN,NaN,NaN,NaN,1921,1929
3,Duke Abbruzzi,Duke,Abbruzzi,Warren,RI,USA,8/3/1917,Rhode Island,NaN,NaN,...,NaN,HB-DB,10-May,175.0,12/6/1982,Newport,RI,NaN,1921,1929
4,Karim Abdul-Jabbar,Karim,Abdul-Jabbar,Los Angeles,CA,USA,6/28/1974,UCLA,Miami Dolphins,3rd,...,1996.0,RB,10-May,194.0,NaN,NaN,NaN,NaN,1996,2000
5,Isa Abdul-Quddus,Isa,Abdul-Quddus,NaN,NaN,NaN,8/3/1989,Fordham,NaN,NaN,...,NaN,S,1-Jun,220.0,NaN,NaN,NaN,NaN,1996,2000
6,Hamza Abdullah,Hamza,Abdullah,Los Angeles,CA,USA,8/20/1983,Washington St.,Tampa Bay Buccaneers,7th,...,2005.0,DB,2-Jun,213.0,NaN,NaN,NaN,NaN,1996,2000
7,Husain Abdullah,Husain,Abdullah,Los Angeles,CA,USA,7/27/1985,Washington St.,NaN,NaN,...,NaN,DB,Jun-00,204.0,NaN,NaN,NaN,NaN,1996,2000
8,Khalid Abdullah,Khalid,Abdullah,Jacksonville,FL,USA,3/6/1979,Mars Hill,Cincinnati Bengals,5th,...,2003.0,LB,2-Jun,227.0,NaN,NaN,NaN,NaN,1996,2000
9,Rabih Abdullah,Rabih,Abdullah,Martinsville,VA,USA,4/27/1975,Lehigh,NaN,NaN,...,NaN,RB,Jun-00,220.0,NaN,NaN,NaN,NaN,1996,2000
10,Rahim Abdullah,Rahim,Abdullah,Jacksonville,FL,USA,3/22/1976,Clemson,Cleveland Browns,2nd,...,1999.0,LB,5-Jun,233.0,NaN,NaN,NaN,NaN,1996,2000
11,Fred Abel,Fred,Abel,Lincoln,NE,USA,7/17/1903,Washington,NaN,NaN,...,NaN,BB-FB,10-May,170.0,8/2/1980,Port Townsend,WA,NaN,1926,1926
12,Bud Abell,Bud,Abell,Kansas City,MO,USA,12/21/1940,Missouri,Kansas City Chiefs,23rd,...,1964.0,LB,3-Jun,220.0,NaN,NaN,NaN,NaN,1926,1926
13,Walter Abercrombie,Walter,Abercrombie,Waco,TX,USA,9/26/1959,Baylor,Pittsburgh Steelers,1st,...,1982.0,RB,Jun-00,210.0,NaN,NaN,NaN,NaN,1926,1926
14,Cliff Aberson,Cliff,Aberson,Chicago,IL,USA,8/28/1921,none,NaN,NaN,...,NaN,TB-DB,Jun-00,195.0,6/23/1973,Vallejo,CA,NaN,1926,1926
15,Victor Abiamiri,Victor,Abiamiri,Baltimore,MD,USA,1/14/1986,Notre Dame,Philadelphia Eagles,2nd,...,2007.0,DE,4-Jun,267.0,NaN,NaN,NaN,NaN,2007,2011
16,Oday Aboushi,Oday,Aboushi,NaN,NaN,NaN,6/5/1991,Virginia,New York Jets,5th,...,2013.0,OT,5-Jun,308.0,NaN,NaN,NaN,NaN,2013,2013
17,Clifton Abraham,Clifton,Abraham,Dallas,TX,USA,12/9/1971,Florida St.,Tampa Bay Buccaneers,5th,...,1995.0,DB,9-May,184.0,NaN,NaN,NaN,NaN,1995,1997
18,Donnie Abraham,Donnie,Abraham,Orangeburg,SC,USA,10/8/1973,East Tennessee St.,Tampa Bay Buccaneers,3rd,...,1996.0,DB,10-May,190.0,NaN,NaN,NaN,NaN,1995,1997
19,John Abraham,John,Abraham,Timmonsville,SC,USA,5/6/1978,South Carolina,New York Jets,1st,...,2000.0,DE,4-Jun,256.0,NaN,NaN,NaN,NaN,1995,1997
20,Robert Abraham,Robert,Abraham,Myrtle Beach,SC,USA,7/13/1960,North Carolina St.,Houston Oilers,3rd,...,1982.0,LB,1-Jun,228.0,NaN,NaN,NaN,NaN,1995,1997
21,Danny Abramowicz,Danny,Abramowicz,Steubenville,OH,USA,7/13/1945,Xavier (OH),New Orleans Saints,17th,...,1967.0,E,1-Jun,195.0,NaN,NaN,NaN,NaN,1995,1997
22,Sid Abramowitz,Sid,Abramowitz,Culver City,CA,USA,5/21/1960,Air Force,Baltimore Colts,5th,...,1983.0,T,6-Jun,280.0,NaN,NaN,NaN,NaN,1995,1997
23,Bobby Abrams,Bobby,Abrams,Detroit,MI,USA,4/12/1967,Michigan,NaN,NaN,...,NaN,LB,3-Jun,240.0,NaN,NaN,NaN,NaN,1995,1997
24,Kevin Abrams,Kevin,Abrams,Tampa,FL,USA,2/28/1974,Syracuse,Detroit Lions,2nd,...,1997.0,DB,8-May,175.0,NaN,NaN,NaN,NaN,1995,1997
25,Nate Abrams,Nate,Abrams,Green Bay,WI,USA,1897-12-25,none,NaN,NaN,...,NaN,E,4-May,145.0,4/30/1941,Green Bay,WI,NaN,1995,1997
26,George Abramson,George,Abramson,Eveleth,MN,USA,5/13/1903,Minnesota,NaN,NaN,...,NaN,G-T,7-May,198.0,3/15/1985,Beverly Hills,CA,NaN,1995,1997
27,Dick Abrell,Dick,Abrell,Linton,IN,USA,1892-05-18,Purdue,NaN,NaN,...,NaN,BB-WB,10-May,172.0,5/5/1973,West Orange,NJ,NaN,1995,1997
28,Ray Abruzzese,Ray,Abruzzese,Philadelphia,PA,USA,10/27/1937,Alabama,Buffalo Bills,23rd,...,1962.0,B,1-Jun,194.0,8/22/2011,Fort Lauderdale,FL,NaN,1995,1997
29,Frank Abruzzino,Frank,Abruzzino,Shinnston,WV,USA,1/22/1908,Colgate,NaN,NaN,...,NaN,BB-LB-C-G-E-WB-,Jun-00,193.0,6/13/1986,Dade County,FL,NaN,1995,1997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23703,Vince Zizak,Vince,Zizak,Camden,NJ,USA,8/8/1908,Villanova,NaN,NaN,...,NaN,G-T,8-May,208.0,NaN,NaN,NaN,NaN,1934,1937
23704,Mickey Zofko,Mickey,Zofko,Melbourne,FL,USA,6/8/1949,Auburn,Detroit Lions,9th,...,1971.0,RB,3-Jun,195.0,NaN,NaN,NaN,NaN,1971,1974
23705,Jon Zogg,Jon,Zogg,San Jose,CA,USA,11/19/1960,Boise St.,NaN,NaN,...,NaN,G,4-Jun,290.0,NaN,NaN,NaN,NaN,1987,1987
23706,Clyde Zoia,Clyde,Zoia,NaN,NaN,NaN,NaN,Notre Dame,NaN,NaN,...,NaN,G,7-May,175.0,4/3/1955,NaN,NaN,NaN,1920,1923
23707,Scott Zolak,Scott,Zolak,Pittsburgh,PA,USA,12/13/1967,Maryland,New England Patriots,4th,...,1991.0,QB,5-Jun,230.0,NaN,NaN,NaN,NaN,1992,1999
23708,Carl Zoll,Carl,Zoll,Howard,WI,USA,1899-01-28,none,NaN,NaN,...,NaN,G,9-May,215.0,10/19/1973,Green Bay,WI,NaN,1992,1999
23709,Dick Zoll,Dick,Zoll,Green Bay,WI,USA,12/10/1913,Indiana,NaN,NaN,...,NaN,G-T,11-May,218.0,9/6/1985,Green Bay,WI,NaN,1992,1999
23710,Marty Zoll,Marty,Zoll,Howard,WI,USA,11/12/1900,none,NaN,NaN,...,NaN,G,8-May,185.0,NaN,NaN,NaN,NaN,1992,1999
23711,Eric Zomalt,Eric,Zomalt,Los Angeles,CA,USA,8/9/1972,California,Philadelphia Eagles,3rd,...,1994.0,DB,11-May,201.0,NaN,NaN,NaN,NaN,1994,1996
23712,Joe Zombek,Joe,Zombek,NaN,NaN,NaN,12/24/1932,Pittsburgh,Pittsburgh Steelers,9th,...,1954.0,DE-E,1-Jun,195.0,1/13/1996,McDonald,PA,NaN,1994,1996
23713,Frank Zombo,Frank,Zombo,Sterling Heights,MI,USA,3/5/1987,Central Michigan,NaN,NaN,...,NaN,LB,3-Jun,254.0,NaN,NaN,NaN,NaN,1994,1996
23714,Lou Zontini,Lou,Zontini,Whitesville,WV,USA,8/30/1917,Notre Dame,NaN,NaN,...,NaN,B,9-May,189.0,8/6/1986,Richmond Heights,OH,NaN,1940,1946
23715,John Zook,John,Zook,Garden City,KS,USA,9/24/1947,Kansas,Los Angeles Rams,4th,...,1969.0,DE,4-Jun,243.0,NaN,NaN,NaN,NaN,1969,1979
23716,Frank Zoppetti,Frank,Zoppetti,NaN,PA,USA,4/15/1916,Duquesne,NaN,NaN,...,NaN,TB,11-May,185.0,NaN,NaN,NaN,NaN,1941,1941
23717,Michael Zordich,Michael,Zordich,NaN,NaN,NaN,10/29/1989,Penn State,NaN,NaN,...,NaN,FB,1-Jun,236.0,NaN,NaN,NaN,NaN,2013,2013
23718,Mike Zordich,Mike,Zordich,Youngstown,OH,USA,10/12/1963,Penn St.,San Diego Chargers,9th,...,1986.0,DB,1-Jun,207.0,NaN,NaN,NaN,NaN,2013,2013
23719,Chris Zorich,Chris,Zorich,Chicago,IL,USA,3/13/1969,Notre Dame,Chicago Bears,2nd,...,1991.0,DT,1-Jun,278.0,NaN,NaN,NaN,NaN,2013,2013
23720,George Zorich,George,Zorich,Wakefield,MI,USA,11/24/1915,Northwestern,NaN,NaN,...,NaN,G-LB,2-Jun,213.0,10/14/1962,Rensselaer,IN,NaN,2013,2013
23721,Jim Zorn,Jim,Zorn,Whittier,CA,USA,5/10/1953,Cal Poly-Pomona,NaN,NaN,...,NaN,QB,2-Jun,200.0,NaN,NaN,NaN,NaN,2013,2013
23722,Vic Zucco,Vic,Zucco,Renton,PA,USA,9/4/1935,Wayne State (MI),Chicago Bears,5th,...,1957.0,DB,Jun-00,187.0,NaN,NaN,NaN,NaN,1957,1960
23723,Greg Zuerlein,Greg,Zuerlein,NaN,NaN,NaN,12/27/1987,Missouri Western St.,St. Louis Rams,6th,...,2012.0,K,Jun-00,187.0,NaN,NaN,NaN,NaN,2012,2013
23724,Dave Zuidmulder,Dave,Zuidmulder,New Franken,WI,USA,2/4/1906,St. Ambrose,NaN,NaN,...,NaN,TB,10-May,175.0,6/8/1978,Green Bay,WI,NaN,1929,1931
23725,Paul Zukauskas,Paul,Zukauskas,Weymouth,MA,USA,7/12/1979,Boston Col.,Cleveland Browns,7th,...,2001.0,G-T,5-Jun,320.0,NaN,NaN,NaN,NaN,2001,2004
23726,Charlie Zunker,Charlie,Zunker,Hanley,TX,USA,8/24/1908,Texas St.,NaN,NaN,...,NaN,T,4-Jun,227.0,6/11/1963,San Antonio,TX,NaN,1934,1934
23727,Albert Zupek,Albert,Zupek,Racine,WI,USA,1/12/1922,Lawrence,NaN,NaN,...,NaN,BB,1-Jun,205.0,6/16/1980,Burlington,IA,NaN,1946,1946
23728,Markus Zusevics,Markus,Zusevics,NaN,NaN,NaN,4/25/1989,Iowa,NaN,NaN,...,NaN,OL,5-Jun,300.0,NaN,NaN,NaN,NaN,2012,2013
23729,Jeremy Zuttah,Jeremy,Zuttah,Edison,NJ,USA,6/1/1986,Rutgers,Tampa Bay Buccaneers,3rd,...,2008.0,G,4-Jun,303.0,NaN,NaN,NaN,NaN,2008,2013
23730,Merle Zuver,Merle,Zuver,Adams,NE,USA,1/25/1905,Nebraska,NaN,NaN,...,NaN,G-C,1-Jun,198.0,3/25/1969,Phoenix,AZ,NaN,1930,1930
23731,Tony Zuzzio,Tony,Zuzzio,Irvington,NJ,USA,8/5/1916,Muhlenberg,NaN,NaN,...,NaN,G,11-May,210.0,4/7/2002,Lawrence,KS,NaN,1942,1942
23732,Jim Zyntell,Jim,Zyntell,Boston,MA,USA,4/27/1910,Holy Cross,NaN,NaN,...,NaN,G,1-Jun,200.0,NaN,NaN,NaN,NaN,1933,1935

In [33]:
roster_09 = pd.read_csv("https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/roster_data/regular_season/reg_roster_2009.csv", sep = ',', header = 0)
roster_09.head()

,season,season_type,full_player_name,abbr_player_name,team,position,gsis_id
0,2009,reg,Aaron Brown,A.Brown,DET,RB,00-0027129
1,2009,reg,Aaron Rodgers,A.Rodgers,GB,QB,00-0023459
2,2009,reg,Aaron Stecker,A.Stecker,ATL,RB,00-0015601
3,2009,reg,Adrian Peterson,A.Peterson,CHI,RB,00-0021306
4,2009,reg,Adrian Peterson,A.Peterson,MIN,RB,00-0025394

In [34]:
roster_10 = pd.read_csv("https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/roster_data/regular_season/reg_roster_2010.csv", sep = ',', header = 0)
roster_10.head()

,season,season_type,full_player_name,abbr_player_name,team,position,gsis_id
0,2010,reg,Aaron Brown,A.Brown,DET,RB,00-0027129
1,2010,reg,Aaron Hernandez,A.Hernandez,NE,TE,00-0027713
2,2010,reg,Aaron Rodgers,A.Rodgers,GB,QB,00-0023459
3,2010,reg,Adrian Arrington,A.Arrington,NO,WR,00-0026377
4,2010,reg,Adrian Peterson,A.Peterson,MIN,RB,00-0025394

In [35]:
roster_11 = pd.read_csv("https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/roster_data/regular_season/reg_roster_2011.csv", sep = ',', header = 0)
roster_11.head()

,season,season_type,full_player_name,abbr_player_name,team,position,gsis_id
0,2011,reg,A.J. Feeley,A.Feeley,STL,QB,00-0020305
1,2011,reg,A.J. Green,A.Green,CIN,WR,00-0027942
2,2011,reg,Aaron Brown,A.Brown,DET,RB,00-0027129
3,2011,reg,Aaron Hernandez,A.Hernandez,NE,TE,00-0027713
4,2011,reg,Aaron Rodgers,A.Rodgers,GB,QB,00-0023459

In [36]:
roster_12 = pd.read_csv("https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/roster_data/regular_season/reg_roster_2012.csv", sep = ',', header = 0)
roster_12.head()

,season,season_type,full_player_name,abbr_player_name,team,position,gsis_id
0,2012,reg,A.J. Green,A.Green,CIN,WR,00-0027942
1,2012,reg,A.J. Jenkins,A.Jenkins,SF,WR,00-0029654
2,2012,reg,Aaron Hernandez,A.Hernandez,NE,TE,00-0027713
3,2012,reg,Aaron Rodgers,A.Rodgers,GB,QB,00-0023459
4,2012,reg,Adrian Peterson,A.Peterson,MIN,RB,00-0025394

In [37]:
roster_13 = pd.read_csv("https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/roster_data/regular_season/reg_roster_2013.csv", sep = ',', header = 0)
roster_13.head()

,season,season_type,full_player_name,abbr_player_name,team,position,gsis_id
0,2013,reg,A.J. Green,A.Green,CIN,WR,00-0027942
1,2013,reg,A.J. Jenkins,A.Jenkins,KC,WR,00-0029654
2,2013,reg,Aaron Dobson,A.Dobson,NE,WR,00-0030540
3,2013,reg,Aaron Rodgers,A.Rodgers,GB,QB,00-0023459
4,2013,reg,Ace Sanders,A.Sanders,JAC,WR,00-0030550

In [41]:
roster_grp_df = pd.concat([roster_09, roster_10, roster_11, roster_12, roster_13],ignore_index=True).drop_duplicates().reset_index(drop=True)
roster_df = roster_grp_df[['season', 'full_player_name', 'abbr_player_name', 'team', 'position']].copy()
roster_df

      season   full_player_name abbr_player_name team position
0       2009        Aaron Brown          A.Brown  DET       RB
1       2009      Aaron Rodgers        A.Rodgers   GB       QB
2       2009      Aaron Stecker        A.Stecker  ATL       RB
3       2009    Adrian Peterson       A.Peterson  CHI       RB
4       2009    Adrian Peterson       A.Peterson  MIN       RB
5       2009     Ahmad Bradshaw       A.Bradshaw  NYG       RB
6       2009        Ahman Green          A.Green   GB       RB
7       2009        Ahmard Hall           A.Hall  TEN       FB
8       2009       Albert Young          A.Young  MIN       RB
9       2009         Alex Smith          A.Smith  PHI       TE
10      2009         Alex Smith          A.Smith   SF       QB
11      2009      Alge Crumpler       A.Crumpler  TEN       TE
12      2009     Andre Caldwell       A.Caldwell  CIN       WR
13      2009        Andre Davis          A.Davis  HOU       WR
14      2009      Andre Johnson        A.Johnson  HOU       WR
15      2009      Anquan Boldin         A.Boldin  ARI       WR
16      2009      Anthony Becht          A.Becht  ARI       TE
17      2009     Anthony Fasano         A.Fasano  MIA       TE
18      2009       Anthony Hill           A.Hill  HOU       TE
19      2009     Antonio Bryant         A.Bryant   TB       WR
20      2009      Antonio Gates          A.Gates   SD       TE
21      2009  Antwaan Randle El             A.El  WAS       WR
22      2009       Arian Foster         A.Foster  HOU       RB
23      2009       Arnaz Battle         A.Battle   SF       WR
24      2009      Austin Collie         A.Collie  IND       WR
25      2009         B.J. Askew          B.Askew   TB       FB
26      2009       Beanie Wells          B.Wells  ARI       RB
27      2009        Bear Pascoe         B.Pascoe  NYG       TE
28      2009       Ben Hartsock       B.Hartsock  NYJ       TE
29      2009        Ben Obomanu        B.Obomanu  SEA       WR
...      ...                ...              ...  ...      ...
2539    2013          Tom Brady          T.Brady   NE       QB
2540    2013       Tom Crabtree       T.Crabtree   TB       TE
2541    2013      Tommy Bohanon        T.Bohanon  NYJ       FB
2542    2013      Tony Gonzalez       T.Gonzalez  ATL       TE
2543    2013          Tony Romo           T.Romo  DAL       QB
2544    2013     Tony Scheffler      T.Scheffler  DET       TE
2545    2013        Tori Gurley         T.Gurley  CLE       WR
2546    2013       Torrey Smith          T.Smith  BAL       WR
2547    2013    Travis Benjamin       T.Benjamin  CLE       WR
2548    2013   Trent Richardson     T.Richardson  IND       RB
2549    2013      Trevor Graham         T.Graham  BUF       WR
2550    2013       Tyler Eifert         T.Eifert  CIN       TE
2551    2013       Tyrod Taylor         T.Taylor  BAL       QB
2552    2013     Vance McDonald       V.McDonald   SF       TE
2553    2013       Vernon Davis          V.Davis   SF       TE
2554    2013       Vick Ballard        V.Ballard  IND       RB
2555    2013        Victor Cruz           V.Cruz  NYG       WR
2556    2013      Vincent Brown          V.Brown   SD       WR
2557    2013    Vincent Jackson        V.Jackson   TB       WR
2558    2013       Virgil Green          V.Green  DEN       TE
2559    2013  Visanthe Shiancoe       V.Shiancoe  TEN       TE
2560    2013        Vonta Leach          V.Leach  BAL       FB
2561    2013         Wes Welker         W.Welker  DEN       WR
2562    2013    Weslye Saunders       W.Saunders  IND       TE
2563    2013     Will Ta'ufo'ou      W.Ta'ufo'ou  JAC       FB
2564    2013     Willis McGahee        W.McGahee  CLE       RB
2565    2013          Zac Stacy          Z.Stacy  STL       RB
2566    2013          Zach Ertz           Z.Ertz  PHI       TE
2567    2013        Zach Miller         Z.Miller  SEA       TE
2568    2013       Zach Sudfeld        Z.Sudfeld  NYJ       TE

[2569 rows x 5 columns]

In [32]:
gameinfo_09 = pd.read_csv("https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/games_data/regular_season/reg_games_2009.csv", sep = ',', header = 0)
gameinfo_09.head()

,type,game_id,home_team,away_team,week,season,state_of_game,game_url,home_score,away_score
0,reg,2009091000,PIT,TEN,1,2009,POST,http://www.nfl.com/liveupdate/game-center/2009...,13,10
1,reg,2009091304,CLE,MIN,1,2009,POST,http://www.nfl.com/liveupdate/game-center/2009...,20,34
2,reg,2009091307,NO,DET,1,2009,POST,http://www.nfl.com/liveupdate/game-center/2009...,45,27
3,reg,2009091308,TB,DAL,1,2009,POST,http://www.nfl.com/liveupdate/game-center/2009...,21,34
4,reg,2009091305,HOU,NYJ,1,2009,POST,http://www.nfl.com/liveupdate/game-center/2009...,7,24